exclude: 'node_modules|.git'
default_stages: [commit]
fail_fast: false


repos:
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        types_or: [python, pyi]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-simplify
        args: [--config, flake8]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.5.1
          - prettier-plugin-tailwindcss@0.1.7
        types: [file]
        types_or: [javascript, vue, html]

ci:
    autoupdate_schedule: weekly
    skip: []
    submodules: false
