name: E2E Tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    name: UI Tests

    services:
      mariadb:
        image: mariadb:10.6
        env:
          MYSQL_ROOT_PASSWORD: frappe
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
    - name: Clone
      uses: actions/checkout@v2

    - name: Check files
      run: |
        python -m compileall -q -f "${GITHUB_WORKSPACE}"
        if grep -lr --exclude-dir=node_modules "^<<<<<<< " "${GITHUB_WORKSPACE}"
            then echo "Found merge conflicts"
            exit 1
        fi

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/*requirements.txt', '**/pyproject.toml', '**/setup.py', '**/setup.cfg') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-ui-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-ui-

    - name: Setup Frappe Bench
      run: |
        bash ${GITHUB_WORKSPACE}/.github/helper/install_dependencies.sh
        bash ${GITHUB_WORKSPACE}/.github/helper/install.sh
      env:
        CI: "Yes"

    - name: Install Playwright Browsers
      run: cd ~/frappe-bench/apps/insights/frontend && yarn playwright install --with-deps

    - name: Run Playwright tests
      run: cd ~/frappe-bench/apps/insights/frontend && yarn playwright test

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
